In [159]:
# importing the dataset
import pandas as pd
import numpy
from sklearn import preprocessing

In [160]:
df_artists = pd.read_csv(r'dataset\artists-data.csv')
df_lyrics = pd.read_csv(r'dataset\lyrics-data.csv')

In [161]:
df=pd.merge(df_artists,df_lyrics,left_on='Link',right_on='ALink')
df_genre=df['Genres'].str.split(';',expand=True)
for colums in df_genre:
    df_genre[colums] = df_genre[colums].str.strip()
df=pd.merge(df,df_genre,left_on=df.index,right_on=df_genre.index)
df.rename(columns={0: "Genre 1", 1: "Genre 2",2: "Genre 3", 3: "Genre 4"}, inplace=True)
df.drop(['SLink', 'key_0','Genres','Link','ALink'], axis=1,inplace=True)

In [162]:
df[['language']].value_counts().head(5)

language
en          191387
pt          156941
es            9916
rw            1679
it            1426
dtype: int64

In [163]:
df

,Artist,Songs,Popularity,SName,Lyric,language,Genre 1,Genre 2,Genre 3,Genre 4
0,Ivete Sangalo,313.0,4.4,Arerê,"Tudo o que eu quero nessa vida,\nToda vida, é\...",pt,Pop,Axé,Romântico,None
1,Ivete Sangalo,313.0,4.4,Se Eu Não Te Amasse Tanto Assim,Meu coração\nSem direção\nVoando só por voar\n...,pt,Pop,Axé,Romântico,None
2,Ivete Sangalo,313.0,4.4,Céu da Boca,É de babaixá!\nÉ de balacubaca!\nÉ de babaixá!...,pt,Pop,Axé,Romântico,None
3,Ivete Sangalo,313.0,4.4,Quando A Chuva Passar,Quando a chuva passar\n\nPra quê falar\nSe voc...,pt,Pop,Axé,Romântico,None
4,Ivete Sangalo,313.0,4.4,Sorte Grande,A minha sorte grande foi você cair do céu\nMin...,pt,Pop,Axé,Romântico,None
...,...,...,...,...,...,...,...,...,...,...
378983,Johnny Clegg,34.0,0.0,The Waiting,Chorus\nHere we stand waiting on the plain\nDa...,en,World Music,Gospel/Religioso,None,None
378984,Johnny Clegg,34.0,0.0,Too Early For The Sky,I nearly disappeared into the mouth of a croco...,en,World Music,Gospel/Religioso,None,None
378985,Johnny Clegg,34.0,0.0,Warsaw 1943 (I Never Betrayed The Revolution),"Amambuka, amambuka azothengisa izwe lakithi, i...",en,World Music,Gospel/Religioso,None,None
378986,Johnny Clegg,34.0,0.0,When The System Has Fallen,Sweat in the heat for days on end\nwaiting for...,en,World Music,Gospel/Religioso,None,None
378987,Johnny Clegg,34.0,0.0,Woman Be My Country,Here we stand on the edge of the day\nFaces me...,en,World Music,Gospel/Religioso,None,None

In [164]:
from collections import Counter

def genre_by_language(language, df=df):
    genre={}
    df_lang = df[df['language']==language]
    dict_0 = df_lang["Genre 1"].value_counts().to_dict()
    dict_1 = df_lang["Genre 2"].value_counts().to_dict()
    dict_2 = df_lang["Genre 3"].value_counts().to_dict()
    dict_3 = df_lang["Genre 4"].value_counts().to_dict()
    genre = Counter(dict_0) + Counter(dict_1) + Counter(dict_2) + Counter(dict_3)
    return(genre)

In [165]:
genre=genre_by_language("en")
sorted(genre.items(), key=lambda t: t[1], reverse=True)

[('Rock', 63717),
 ('Pop', 33571),
 ('Pop/Rock', 26360),
 ('Heavy Metal', 21759),
 ('Hip Hop', 20902),
 ('Indie', 20134),
 ('Romântico', 17947),
 ('Hard Rock', 17250),
 ('Rap', 17114),
 ('R&B', 15581),
 ('Rock Alternativo', 13061),
 ('Black Music', 13024),
 ('Dance', 11895),
 ('Folk', 11124),
 ('Country', 10630),
 ('Punk Rock', 9215),
 ('Soul Music', 8131),
 ('Electronica', 7799),
 ('Gospel/Religioso', 7337),
 ('Hardcore', 7082),
 ('Trilha Sonora', 6213),
 ('Blues', 6094),
 ('Gótico', 4984),
 ('Soft Rock', 4483),
 ('Progressivo', 4365),
 ('Jazz', 4343),
 ('Tecnopop', 3873),
 ('Pós-Punk', 3274),
 ('Reggae', 3207),
 ('Rockabilly', 3100),
 ('New Wave', 3075),
 ('Pop/Punk', 3039),
 ('Disco', 2890),
 ('Grunge', 2752),
 ('Funk', 2454),
 ('Psicodelia', 2258),
 ('Clássico', 2170),
 ('Instrumental', 1909),
 ('Surf Music', 1901),
 ('House', 1785),
 ('Emocore', 1689),
 ('Axé', 1620),
 ('Classic Rock', 1533),
 ('COLETÂNEA', 1392),
 ('J-Pop/J-Rock', 1230),
 ('Infantil', 1220),
 ('Trip-Hop', 1203),
 ('Ska', 1200),
 ('New Age', 1117),
 ('Industrial', 1004),
 ('Chillout', 974),
 ('Piano Rock', 965),
 ('Power-Pop', 917),
 ('MPB', 768),
 ('World Music', 680),
 ('Trance', 659),
 ('K-Pop/K-Rock', 632),
 ('Funk Carioca', 585),
 ('Metal', 432),
 ('Bossa Nova', 375),
 ('Velha Guarda', 226),
 ('Sertanejo', 198),
 ('Tropical House', 168),
 ('Jovem Guarda', 150),
 ('Post-Rock', 136),
 ('Trap', 116),
 ('Lo-fi', 86),
 ('Samba', 82),
 ('Fado', 41),
 ('Reggaeton', 35),
 ('Pagode', 29),
 ('Forró', 18),
 ('Kizomba', 7),
 ('Electro Swing', 6),
 ('Regional', 2)]

In [166]:
first_genre=genre="Rock"
first_lg="en"

In [167]:
df=df.iloc[df.index[(df['Genre 1']==first_genre) | (df['Genre 2']==first_genre) | (df['Genre 3']==first_genre) | (df['Genre 4']==first_genre)].tolist()]
df=df[df['language']==first_lg]
df.drop(['language', 'Genre 1','Genre 2','Genre 3','Genre 4'], axis=1,inplace=True)
df

,Artist,Songs,Popularity,SName,Lyric
16609,Elvis Presley,759.0,23.1,Can't Help Falling In Love,"Wise men say, only fools rush in\nBut I can't ..."
16610,Elvis Presley,759.0,23.1,Suspicious Minds,We're caught in a trap\nI can't walk out\nBeca...
16611,Elvis Presley,759.0,23.1,Always On My Mind,"Maybe I didn't treat you,\nQuite as good as I ..."
16612,Elvis Presley,759.0,23.1,Love Me Tender,"Love me tender, love me sweet,\nNever let me g..."
16613,Elvis Presley,759.0,23.1,My Way,And now the end is near\nAnd so I face the fin...
...,...,...,...,...,...
375531,Club Penguin,11.0,0.0,Party in my Iggy,I wonder what's that funky sound\nfrom around ...
375532,Club Penguin,11.0,0.0,The Party Starts Now,Get up Party Penguins come on haven't you hear...
375533,Club Penguin,11.0,0.0,We Are the Penguins - Dj Cadence,Check one\nTurn the volume up\nAnd join the cl...
375534,Club Penguin,11.0,0.0,You Gotta Have Wigman (Puffle Party),"Puffle party, party, party, party, party\n\nWe..."
375535,Club Penguin,11.0,0.0,You've Got This,All you need is a beat\nThat could make the gr...

In [180]:
df2 = df[df.Popularity > 10]
df2

,Artist,Songs,Popularity,SName,Lyric
16609,Elvis Presley,759.0,23.1,Can't Help Falling In Love,"Wise men say, only fools rush in\nBut I can't ..."
16610,Elvis Presley,759.0,23.1,Suspicious Minds,We're caught in a trap\nI can't walk out\nBeca...
16611,Elvis Presley,759.0,23.1,Always On My Mind,"Maybe I didn't treat you,\nQuite as good as I ..."
16612,Elvis Presley,759.0,23.1,Love Me Tender,"Love me tender, love me sweet,\nNever let me g..."
16613,Elvis Presley,759.0,23.1,My Way,And now the end is near\nAnd so I face the fin...
...,...,...,...,...,...
313529,4 Non Blondes,15.0,10.1,Misty Mountain Hop,"Walkin' in the park just the other day, baby,\..."
313530,4 Non Blondes,15.0,10.1,Morphine And Chocolate,Substitute my gloom with happiness\nSubstitute...
313531,4 Non Blondes,15.0,10.1,No Place Like Home,When I wake up in my house\nI get dressed then...
313532,4 Non Blondes,15.0,10.1,Old Mr. Heffer,Stumbled my way on the darkest afternoon\nI go...
313533,4 Non Blondes,15.0,10.1,Superfly,Here i am and i'm waitin' on a chance to make ...

In [188]:
df3=df2.drop_duplicates(subset='Artist')
df4=df2.drop_duplicates(subset='Artist',keep='last')
df3=pd.concat([df3,df4])

In [189]:
df3

,Artist,Songs,Popularity,SName,Lyric
16609,Elvis Presley,759.0,23.1,Can't Help Falling In Love,"Wise men say, only fools rush in\nBut I can't ..."
17590,Rolling Stones,438.0,12.8,Sympathy For The Devil,Please allow me to introduce myself\nI'm a man...
27576,AC/DC,204.0,19.2,Back In Black,"Back in black, I hit the sack,\nI've been too ..."
28420,Pink Floyd,208.0,42.6,"Another Brick In The Wall (part 1,2, 3)",Parte1\nDaddy's flown across the ocean\nLeavin...
31645,Creedence Clearwater Revival,67.0,13.7,Have You Ever Seen The Rain?,Someone told me long ago\nThere's a calm befor...
...,...,...,...,...,...
287715,Red Hot Chili Peppers,267.0,41.4,Your Eyes Girl,I'm afraid that i'm never afraid\nI've got com...
312737,John Lennon,135.0,43.8,Your Hands,Anatano te\nKonnani kireina\nAnatano te\nYumen...
313008,Bryan Adams,271.0,20.8,Young Lust,I am just a new boy\nStranger in this town\nWh...
313461,Rod Stewart,453.0,16.2,Your Song,It's a little bit funny this feeling inside\nI...
313533,4 Non Blondes,15.0,10.1,Superfly,Here i am and i'm waitin' on a chance to make ...

In [192]:
df=df3.drop(['Artist', 'Songs','Popularity','SName'], axis=1)

In [193]:
df

                                                    Lyric
16609   Wise men say, only fools rush in\nBut I can't ...
17590   Please allow me to introduce myself\nI'm a man...
27576   Back in black, I hit the sack,\nI've been too ...
28420   Parte1\nDaddy's flown across the ocean\nLeavin...
31645   Someone told me long ago\nThere's a calm befor...
...                                                   ...
287715  I'm afraid that i'm never afraid\nI've got com...
312737  Anatano te\nKonnani kireina\nAnatano te\nYumen...
313008  I am just a new boy\nStranger in this town\nWh...
313461  It's a little bit funny this feeling inside\nI...
313533  Here i am and i'm waitin' on a chance to make ...

[90 rows x 1 columns]

In [194]:
df.to_csv('dataset\lyrics_clean.csv',index=False)

In [195]:
import sqlite3

conn = sqlite3.connect('database.db')
c = conn.cursor()
c.execute('CREATE TABLE IF NOT EXISTS lyrics (lyrics)')
conn.commit()

df.to_sql("lyrics", conn, if_exists='replace', index=False)

90